/*
 * Copyright 2014 Denison.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ide.gui;

import ide.gui.code.DocumentAssembly6502;
import ide.Projeto;
import ide.Recursos;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Denison
 */
public class Atari2600IDE extends javax.swing.JFrame {

    private final ProjectsList projetos;
    private final NewProject newProjectFrame;
    private Projeto projetoAtual;
    private final JStella jStella2;

    /**
     * Creates new form Atari2600IDE
     */
    public Atari2600IDE() {
        projetos = new ProjectsList();
        jStella2 = new JStella();
        newProjectFrame = new NewProject(this, true);
        newProjectFrame.setProjetos(projetos);
        projetoAtual = null;
        initComponents();
        jTabbedPane1.addTab("JStella", jStella2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JToolBar jToolBar1 = new javax.swing.JToolBar();
        javax.swing.JButton jButtonSave = new javax.swing.JButton();
        javax.swing.JButton jButtonPlay = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JScrollPane jScrollPaneWelcome = new javax.swing.JScrollPane();
        javax.swing.JTextPane jTextPaneWelcome = new javax.swing.JTextPane();
        javax.swing.JScrollPane jScrollPaneNotificacoes = new javax.swing.JScrollPane();
        jTextAreaNotificacoes = new javax.swing.JTextArea();
        javax.swing.JScrollPane jScrollPaneList = new javax.swing.JScrollPane();
        jListProjetos = new javax.swing.JList();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenuFile = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItemNew = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemSave = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemExclude = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemClose = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemExit = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenuEdit = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItemUndo = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemRedo = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem jMenuItemCut = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemCopy = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemPaste = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(ide.Recursos.LOGO.getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/document-save_1.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.setFocusable(false);
        jButtonSave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSave);

        jButtonPlay.setForeground(new java.awt.Color(0, 153, 0));
        jButtonPlay.setText("Play ►");
        jButtonPlay.setFocusable(false);
        jButtonPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonPlay);

        jButtonStop.setForeground(new java.awt.Color(255, 0, 0));
        jButtonStop.setText("Stop ▇");
        jButtonStop.setEnabled(false);
        jButtonStop.setFocusable(false);
        jButtonStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonStop);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jTextPaneWelcome.setEditable(false);
        jTextPaneWelcome.setContentType("text/html"); // NOI18N
        try {
            jTextPaneWelcome.setPage(Recursos.HTML);
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        jScrollPaneWelcome.setViewportView(jTextPaneWelcome);

        jTabbedPane1.addTab("Welcome", jScrollPaneWelcome);

        jTextAreaNotificacoes.setColumns(20);
        jTextAreaNotificacoes.setRows(5);
        jTextAreaNotificacoes.setText("Welcome\n\nAtari 2600 IDE v1.0\n\n");
        jScrollPaneNotificacoes.setViewportView(jTextAreaNotificacoes);

        jListProjetos.setModel(projetos);
        jListProjetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProjetos.setCellRenderer(projetos);
        jListProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProjetosMouseClicked(evt);
            }
        });
        jScrollPaneList.setViewportView(jListProjetos);

        jMenuFile.setText("File");

        jMenuItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/icon_project.png"))); // NOI18N
        jMenuItemNew.setText("New Project...");
        jMenuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemNew);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/insert-object_1.png"))); // NOI18N
        jMenuItem1.setText("New File");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem1);

        jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/document-save_1.png"))); // NOI18N
        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSave);

        jMenuItemExclude.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExclude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/edit-delete.png"))); // NOI18N
        jMenuItemExclude.setText("Exclude");
        jMenuItemExclude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcludeActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExclude);

        jMenuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/document-close.png"))); // NOI18N
        jMenuItemClose.setText("Close");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemClose);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/window-close.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/edit-undo.png"))); // NOI18N
        jMenuItemUndo.setText("Undo");
        jMenuItemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUndoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemUndo);

        jMenuItemRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/edit-redo.png"))); // NOI18N
        jMenuItemRedo.setText("Redo");
        jMenuItemRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRedoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemRedo);
        jMenuEdit.add(jSeparator1);

        jMenuItemCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/edit-cut.png"))); // NOI18N
        jMenuItemCut.setText("Cut");
        jMenuItemCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCutActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemCut);

        jMenuItemCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/edit-copy.png"))); // NOI18N
        jMenuItemCopy.setText("Copy");
        jMenuItemCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCopyActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemCopy);

        jMenuItemPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/gui/imgs/edit-paste.png"))); // NOI18N
        jMenuItemPaste.setText("Paste");
        jMenuItemPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPasteActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemPaste);

        jMenuBar1.add(jMenuEdit);

        jMenu1.setText("Config");

        jMenuItem2.setText("Project Dir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Assembler");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jScrollPaneList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jTabbedPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneList, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        if (projetoAtual != null && !projetoAtual.isFile()) {
            try {
                if (!projetoAtual.getSalvo()) {
                    salvar(projetoAtual);
                }
                System.out.println("\nAssemble...\n");
                String result = Recursos.assembler(projetoAtual);
                if (result.endsWith("\nComplete.\n")) {
                    System.out.println(result);
                    try (FileInputStream zFIS = new FileInputStream(projetoAtual.getRomFile())) {
                        jStella2.getIntercessor().playROM(zFIS);
                        jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount() - 1);
                        jButtonStop.setEnabled(true);
                        zFIS.close();
                    }
                } else {
                    System.err.println(result);
                }
            } catch (IOException ex) {
                System.err.println(ex.getMessage());
            }
        } else {
            System.err.println("First open a project!");
        }
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        jStella2.closeRom();
        jButtonStop.setEnabled(false);
        if (projetoAtual != null) {
            for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
                if (jTabbedPane1.getTitleAt(i).equals(projetoAtual.getNome())) {
                    jTabbedPane1.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jListProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProjetosMouseClicked
        if (evt.getClickCount() == 2) {
            if (!foco((Projeto) jListProjetos.getSelectedValue())) {
                abrir((Projeto) jListProjetos.getSelectedValue());
                System.out.println(projetoAtual.getNome() + " is open");
            }
        } else {
            Projeto proj = (Projeto) jListProjetos.getSelectedValue();
            foco(proj);
        }
    }//GEN-LAST:event_jListProjetosMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        int index = jTabbedPane1.getSelectedIndex();
        if (index > 0 && index < jTabbedPane1.getTabCount()) {
            if (projetoAtual == null || !projetoAtual.getNome().equals(jTabbedPane1.getTitleAt(index))) {
                String projNome = jTabbedPane1.getTitleAt(index);
                for (int i = 0; i < projetos.getSize(); i++) {
                    Projeto proj = (Projeto) projetos.get(i);
                    if (proj.getNome().equals(projNome)) {
                        setTitle(proj.toString());
                        projetoAtual = proj;
                    }
                }
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jMenuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewActionPerformed
        int projs = projetos.getSize();
        newProjectFrame.setVisible(true);
        if (projetos.getSize() > projs) {
            abrir(projetos.get(projs));
        }
    }//GEN-LAST:event_jMenuItemNewActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        if (projetoAtual != null && !projetoAtual.getSalvo()) {
            salvar(projetoAtual);
        }
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        if (projetoAtual != null) {
            if (!projetoAtual.getSalvo()) {
                int escolha = JOptionPane.showConfirmDialog(this, "Do you want to save changes?");
                if (escolha == JOptionPane.YES_OPTION) {
                    salvar(projetoAtual);
                }
            }
            for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
                if (jTabbedPane1.getTitleAt(i).equals(projetoAtual.getNome())) {
                    jTabbedPane1.removeTabAt(i);
                    setTitle("Atari 2600 IDE");
                    System.out.println(projetoAtual.getNome() + " is closed");
                    projetoAtual = null;
                    break;
                }
            }
        }
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    private void jMenuItemExcludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcludeActionPerformed
        Projeto proj = (Projeto) jListProjetos.getSelectedValue();
        if (proj != null) {
            String texto = "Do you really want to delete the ";
            if (proj.isFile()) {
                texto += "file ";
            } else {
                texto += "project ";
            }
            int opcao = JOptionPane.showConfirmDialog(this,
                    texto + proj.getNome() + " ?",
                    "Confirm",
                    JOptionPane.YES_NO_OPTION);
            if (opcao == JOptionPane.YES_OPTION) {
                //Caso seja o projeto atual tira a referencia
                if (proj.equals(projetoAtual)) {
                    setTitle("Atari 2600 IDE");
                    projetoAtual = null;
                }
                //Fecha a aba aberta
                for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
                    if (jTabbedPane1.getTitleAt(i).equals(proj.getNome())) {
                        jTabbedPane1.removeTabAt(i);
                        break;
                    }
                }
                //Fecha demais abas
                if (!proj.isFile()) {
                    for (File file : proj.getDiretorio().listFiles()) {
                        for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
                            if (jTabbedPane1.getTitleAt(i).equals(file.getName())) {
                                jTabbedPane1.removeTabAt(i);
                                break;
                            }
                        }
                    }
                }
                //Deleta arquivos
                proj.delete();
                //Remove dos projetos
                int pos = projetos.indexOf(proj);
                projetos.removeElement(proj);
                while (pos < projetos.size() && projetos.get(pos).isFile()) {
                    projetos.remove(pos);
                }
            }
        }
    }//GEN-LAST:event_jMenuItemExcludeActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        jMenuItemSaveActionPerformed(evt);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jMenuItemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUndoActionPerformed
        JTextPane text = getSelectText();
        if (text != null) {
            ((DocumentAssembly6502) text.getDocument()).undo();
        }
    }//GEN-LAST:event_jMenuItemUndoActionPerformed

    private void jMenuItemRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRedoActionPerformed
        JTextPane text = getSelectText();
        if (text != null) {
            ((DocumentAssembly6502) text.getDocument()).redo();
        }
    }//GEN-LAST:event_jMenuItemRedoActionPerformed

    private void jMenuItemCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCutActionPerformed
        JTextPane text = getSelectText();
        if (text != null) {
            text.cut();
        }
    }//GEN-LAST:event_jMenuItemCutActionPerformed

    private void jMenuItemCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopyActionPerformed
        JTextPane text = getSelectText();
        if (text != null) {
            text.copy();
        }
    }//GEN-LAST:event_jMenuItemCopyActionPerformed

    private void jMenuItemPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPasteActionPerformed
        JTextPane text = getSelectText();
        if (text != null) {
            text.paste();
        }
    }//GEN-LAST:event_jMenuItemPasteActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        boolean cancel = false;
        for (int i = 0; i < projetos.getSize(); i++) {
            Projeto proj = projetos.get(i);
            if (!proj.getSalvo()) {
                int escolha = JOptionPane.showConfirmDialog(this, "Do you want to save changes on " + proj.getNome() + "?");
                if (escolha == JOptionPane.YES_OPTION) {
                    salvar(projetoAtual);
                } else if (escolha == JOptionPane.CANCEL_OPTION) {
                    cancel = true;
                    break;
                }
            }
        }
        if (!cancel) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jMenuItemExitActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Projeto proj = (Projeto) jListProjetos.getSelectedValue();
        if (proj != null && !proj.isFile()) {
            String nome = JOptionPane.showInputDialog(this, "Enter the file name");
            if (!nome.equals("")) {
                File arquivo = new File(proj.getDiretorio(), nome + ".h");
                try {
                    arquivo.createNewFile();
                    int index = projetos.indexOf(proj);
                    projetos.add(index + 1, new Projeto(arquivo));
                } catch (IOException ex) {
                    System.err.println(ex);
                }
            } else {
                System.err.println("Invalid name");
            }
        } else {
            System.err.println("Select a project");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(this, Recursos.PROJECTS_DIR.getAbsoluteFile());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String newFile = JOptionPane.showInputDialog(this, "You can change!", Recursos.MONTADOR);
        if (newFile != null && !newFile.equals(Recursos.MONTADOR)) {
            File novo = new File(newFile);
            if (novo.exists()) {
                Recursos.MONTADOR = newFile;
            } else {
                System.err.println("Can't change");
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void modificar() {
        if (projetoAtual != null && projetoAtual.getSalvo()) {
            projetoAtual.setSalvo(false);
            setTitle(projetoAtual.toString());
        }
    }

    /**
     * Cria nova tab para o projeto
     *
     * @param proj
     */
    private void abrir(Projeto proj) {
        projetoAtual = proj;
        setTitle(projetoAtual.toString());
        JTextPane projctPane = new JTextPane();
        JScrollPane scroll = new JScrollPane(projctPane);
        DocumentAssembly6502 doc = new DocumentAssembly6502();
        doc.configurarTextComponent(projctPane);
        try {
            doc.insertString(0, projetoAtual.getSource(), null);
        } catch (BadLocationException ex) {
            System.err.println(ex.getMessage());
        }
        // Evento verifica alterações
        doc.addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                modificar();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                modificar();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        scroll.setRowHeaderView(doc.getLinhas());
        scroll.setColumnHeaderView(doc.getCursor());
        if (projetoAtual.isFile()) {
            jTabbedPane1.insertTab(projetoAtual.getNome(), null, scroll, "tooltip", 1);
        } else {
            jTabbedPane1.insertTab(projetoAtual.getNome(), Recursos.ICON, scroll, "tooltip", 1);
        }
        jTabbedPane1.setSelectedIndex(1);
    }

    private boolean foco(Projeto proj) {
        for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
            if (jTabbedPane1.getTitleAt(i).equals(proj.getNome())) {
                projetoAtual = proj;
                setTitle(proj.toString());
                jTabbedPane1.setSelectedIndex(i);
                return true;
            }
        }
        return false;
    }

    private void salvar(Projeto proj) {
        JTextPane text = null;
        for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
            if (jTabbedPane1.getTitleAt(i).equals(proj.getNome())) {
                JScrollPane jsp = (JScrollPane) jTabbedPane1.getComponentAt(i);
                text = (JTextPane) jsp.getViewport().getView();
                break;
            }
        }
        if (text != null) {
            proj.save(text.getText());
            setTitle(proj.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStop;
    private javax.swing.JList jListProjetos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaNotificacoes;
    // End of variables declaration//GEN-END:variables

    public JTextArea getNotificacoes() {
        return jTextAreaNotificacoes;
    }

    private JTextPane getSelectText() {
        int index = jTabbedPane1.getSelectedIndex();
        if (index > 0 && index < jTabbedPane1.getTabCount()) {
            JScrollPane jsp = (JScrollPane) jTabbedPane1.getSelectedComponent();
            return (JTextPane) jsp.getViewport().getView();
        }
        return null;
    }

}
